### PR TITLE
v0.9.4

### PR DESCRIPTION
**Pull request by josephmiclaus**

### CODE REVIEW

**Comment by abisz** [comment]
Can we wait unitl tomorrow with the merge? I would like to finish my tasks but won't be able to do so until tomorrow morning!

**Comment by josephmiclaus** [comment]
@abisz sure !

Just move back the issues you need from milestone [v.0.9.5](https://github.com/fhstp-mfg/mobilot/milestone/4) to v.0.9.4 please.

**Comment by abisz** [comment]
I merged my feature branch and fixed a few issues, I'm good for merging this one!

**Comment by josephmiclaus** [comment]
@abisz thank you !

**Pull request merged**
